// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpb9i2SBJASFO_Q5Og8rhZedZed_l9fBo',
    appId: '1:437605764015:web:6ec5666d9376ce4539bd5a',
    messagingSenderId: '437605764015',
    projectId: 'duplo-aa699',
    authDomain: 'duplo-aa699.firebaseapp.com',
    storageBucket: 'duplo-aa699.firebasestorage.app',
    measurementId: 'G-NHTPF72DB7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCb7ZZ03nOQoWIIu1KtWbedNo6C57C_c_Q',
    appId: '1:437605764015:android:f6b78d6219a4136639bd5a',
    messagingSenderId: '437605764015',
    projectId: 'duplo-aa699',
    storageBucket: 'duplo-aa699.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxUpbGOohnP6QBeIZAJNdZkziFyYc12QA',
    appId: '1:437605764015:ios:64f63703a51a208b39bd5a',
    messagingSenderId: '437605764015',
    projectId: 'duplo-aa699',
    storageBucket: 'duplo-aa699.firebasestorage.app',
    iosBundleId: 'com.example.duplo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxUpbGOohnP6QBeIZAJNdZkziFyYc12QA',
    appId: '1:437605764015:ios:64f63703a51a208b39bd5a',
    messagingSenderId: '437605764015',
    projectId: 'duplo-aa699',
    storageBucket: 'duplo-aa699.firebasestorage.app',
    iosBundleId: 'com.example.duplo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpb9i2SBJASFO_Q5Og8rhZedZed_l9fBo',
    appId: '1:437605764015:web:03a84ddc7632fce939bd5a',
    messagingSenderId: '437605764015',
    projectId: 'duplo-aa699',
    authDomain: 'duplo-aa699.firebaseapp.com',
    storageBucket: 'duplo-aa699.firebasestorage.app',
    measurementId: 'G-VNNEQYYPWG',
  );
}
